# Generated by Django 5.2.8 on 2025-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityTest',
            fields=[
                ('test_id', models.AutoField(db_column='Test_ID', primary_key=True, serialize=False)),
                ('test_type', models.CharField(db_column='Test_Type', max_length=50)),
                ('test_date', models.DateField(db_column='Test_Date')),
                ('test_result', models.CharField(db_column='Test_Result', max_length=20)),
                ('compatibility_score', models.DecimalField(blank=True, db_column='Compatibility_Score', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'compatibility_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(db_column='Donor_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('date_of_birth', models.DateField(db_column='Date_of_Birth')),
                ('blood_type', models.CharField(db_column='Blood_Type', max_length=3)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=5, null=True)),
                ('contact_info', models.CharField(blank=True, db_column='Contact_Info', max_length=255, null=True)),
                ('donor_type', models.CharField(db_column='Donor_Type', max_length=8)),
                ('medical_history', models.CharField(blank=True, db_column='Medical_History', max_length=256, null=True)),
                ('cause_of_death', models.CharField(blank=True, db_column='Cause_of_Death', max_length=255, null=True)),
                ('registration_date', models.DateField(db_column='Registration_Date')),
                ('medical_clearance_date', models.DateField(blank=True, db_column='Medical_Clearance_Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=8, null=True)),
            ],
            options={
                'db_table': 'donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonorEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField(db_column='Contact_Number')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('relationship', models.CharField(blank=True, db_column='Relationship', max_length=50, null=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, db_column='Alternate_Phone', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, db_column='Street_number', max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, db_column='Street_name', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'donor_emergency_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpAppointment',
            fields=[
                ('appointment_id', models.AutoField(db_column='Appointment_ID', primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(db_column='Appointment_Date')),
                ('appointment_time', models.TimeField(blank=True, db_column='Appointment_Time', null=True)),
                ('rejection_indicators', models.CharField(blank=True, db_column='Rejection_Indicators', max_length=255, null=True)),
                ('lab_results', models.CharField(blank=True, db_column='Lab_Results', max_length=256, null=True)),
                ('medication_adherence', models.CharField(blank=True, db_column='Medication_Adherence', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=256, null=True)),
                ('next_appointment_date', models.DateField(blank=True, db_column='Next_Appointment_Date', null=True)),
            ],
            options={
                'db_table': 'follow_up_appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(db_column='Hospital_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, db_column='Street_number', max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, db_column='Street_name', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('trauma_level', models.IntegerField(blank=True, db_column='Trauma_Level', null=True)),
                ('opo_affiliation', models.CharField(blank=True, db_column='OPO_Affiliation', max_length=100, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hospital_capabilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('staff_id', models.AutoField(db_column='Staff_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('specialization', models.CharField(db_column='Specialization', max_length=18)),
                ('license_number', models.CharField(blank=True, db_column='License_Number', max_length=50, null=True, unique=True)),
                ('certification_date', models.DateField(blank=True, db_column='Certification_Date', null=True)),
                ('certification_level', models.CharField(blank=True, db_column='Certification_Level', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'medical_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(db_column='Medication_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('dosage_form', models.CharField(blank=True, db_column='Dosage_Form', max_length=50, null=True)),
                ('typical_dosage', models.CharField(blank=True, db_column='Typical_Dosage', max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, db_column='Purpose', max_length=100, null=True)),
                ('side_effects', models.CharField(blank=True, db_column='Side_Effects', max_length=256, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=100, null=True)),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('organ_id', models.AutoField(db_column='Organ_ID', primary_key=True, serialize=False)),
                ('hla_type', models.CharField(blank=True, db_column='HLA_Type', max_length=50, null=True)),
                ('procurement_date', models.DateField(db_column='Procurement_Date')),
                ('procurement_time', models.TimeField(db_column='Procurement_Time')),
                ('size_weight', models.DecimalField(blank=True, db_column='Size_Weight', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=12, null=True)),
            ],
            options={
                'db_table': 'organ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganAllocation',
            fields=[
                ('allocation_id', models.AutoField(db_column='Allocation_ID', primary_key=True, serialize=False)),
                ('allocation_date', models.DateTimeField(db_column='Allocation_Date')),
                ('match_score', models.DecimalField(blank=True, db_column='Match_Score', decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, db_column='Response_Deadline', null=True)),
            ],
            options={
                'db_table': 'organ_allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganType',
            fields=[
                ('type_name', models.CharField(db_column='Type_Name', max_length=30, primary_key=True, serialize=False)),
                ('typical_viability_hours', models.IntegerField(db_column='Typical_Viability_Hours')),
                ('cold_ischemia_time_max', models.IntegerField(db_column='Cold_Ischemia_Time_Max')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=256, null=True)),
                ('special_requirements', models.CharField(blank=True, db_column='Special_Requirements', max_length=256, null=True)),
            ],
            options={
                'db_table': 'organ_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(db_column='Recipient_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('date_of_birth', models.DateField(db_column='Date_of_Birth')),
                ('blood_type', models.CharField(db_column='Blood_Type', max_length=3)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=5, null=True)),
                ('contact_info', models.CharField(blank=True, db_column='Contact_Info', max_length=255, null=True)),
                ('medical_history', models.CharField(blank=True, db_column='Medical_History', max_length=256, null=True)),
                ('primary_diagnosis', models.CharField(blank=True, db_column='Primary_Diagnosis', max_length=255, null=True)),
                ('medical_urgency_level', models.IntegerField(blank=True, db_column='Medical_Urgency_Level', null=True)),
                ('registration_date', models.DateField(db_column='Registration_Date')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=12, null=True)),
                ('insurance_info', models.CharField(blank=True, db_column='Insurance_Info', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recipient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField(db_column='Contact_Number')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('relationship', models.CharField(blank=True, db_column='Relationship', max_length=50, null=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, db_column='Alternate_Phone', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, db_column='Street_number', max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, db_column='Street_name', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'recipient_emergency_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_column='Start_Date')),
                ('end_date', models.DateField(blank=True, db_column='End_Date', null=True)),
                ('dosage', models.CharField(db_column='Dosage', max_length=50)),
                ('frequency', models.CharField(db_column='Frequency', max_length=50)),
            ],
            options={
                'db_table': 'recipient_medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.DecimalField(blank=True, db_column='Priority_Score', decimal_places=2, max_digits=5, null=True)),
                ('wait_list_date', models.DateField(db_column='Wait_List_Date')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('meld_score', models.DecimalField(blank=True, db_column='MELD_Score', decimal_places=2, max_digits=5, null=True)),
                ('cpra_score', models.DecimalField(blank=True, db_column='CPRA_Score', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'recipient_waitlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(db_column='Surgery_ID', primary_key=True, serialize=False)),
                ('surgery_date', models.DateField(db_column='Surgery_Date')),
                ('surgery_time', models.TimeField(blank=True, db_column='Surgery_Time', null=True)),
                ('duration_hours', models.DecimalField(blank=True, db_column='Duration_Hours', decimal_places=2, max_digits=4, null=True)),
                ('outcome', models.CharField(blank=True, db_column='Outcome', max_length=13, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=256, null=True)),
                ('complications_description', models.CharField(blank=True, db_column='Complications_Description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'surgery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurgeryPerformedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_column='Role', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, db_column='Start_Time', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='End_Time', null=True)),
                ('primary_surgeon', models.IntegerField(blank=True, db_column='Primary_Surgeon', null=True)),
            ],
            options={
                'db_table': 'surgery_performed_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password_hash', models.CharField(db_column='Password_Hash', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('role', models.CharField(db_column='Role', max_length=13)),
                ('account_status', models.CharField(blank=True, db_column='Account_Status', max_length=9, null=True)),
                ('created_date', models.DateField(db_column='Created_Date')),
                ('last_login', models.DateTimeField(blank=True, db_column='Last_Login', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
